#!/usr/bin/env python3
"""Provision ERPNext on Railway from scratch.

This is the record of how the live deployment was built, and the way to rebuild it
(new project, new environment, or disaster recovery). It creates services, so run it
against a NEW project — it is not a repeated sync.

    railway init -n erpnext          # create + link the project first
    python3 railway/provision.py

Prerequisites: railway CLI logged in, and this repo pushed to GitHub and visible to
Railway's GitHub App (the erpnext service is built from it).

Three Railway quirks this works around, all discovered the hard way (same as the
plane deployment this was adapted from):

  1. `railway volume add -s <svc>` panics with a Rust unwrap error. You must
     `railway service link <svc>` first, then call `railway volume add` bare.
     Volume creation is also rate-limited, hence the retry.
  2. `railway add -r <owner/repo>` reports "repo not found" for a repo created
     minutes earlier — the CLI's repo list is cached. The GraphQL API sees it
     immediately, so the repo-backed service is created through the API.
  3. Start commands and root directories are not CLI flags at all. They go through
     serviceInstanceUpdate. There is no DOCKERFILE builder enum — Railway
     auto-detects a Dockerfile inside rootDirectory.

Python's SSL store is not configured on this machine, so HTTP goes through curl.
"""
import json, os, secrets, subprocess, sys, time

GH_REPO = os.environ.get("GH_REPO", "DigitalEstateMedia/erpnext")
API = "https://backboard.railway.com/graphql/v2"
HERE = os.path.dirname(os.path.abspath(__file__))
ENV_FILE = os.path.join(HERE, ".env.local")

TOKEN = json.load(open(os.path.expanduser("~/.railway/config.json")))["user"]["token"]


def gql(query, variables=None):
    body = json.dumps({"query": query, "variables": variables or {}})
    out = subprocess.run(
        ["curl", "-sS", "-X", "POST", API,
         "-H", f"Authorization: Bearer {TOKEN}",
         "-H", "Content-Type: application/json", "--data-binary", body],
        capture_output=True, text=True, timeout=120).stdout
    r = json.loads(out)
    if "errors" in r:
        raise SystemExit(f"GraphQL error: {json.dumps(r['errors'])[:400]}")
    return r["data"]


def sh(*args, check=True):
    return subprocess.run(args, capture_output=True, text=True, check=check).stdout


# ---------------------------------------------------------------- secrets
if not os.path.exists(ENV_FILE):
    hexs = lambda n: secrets.token_hex(n)
    with open(ENV_FILE, "w") as f:
        f.write(
            "# Generated by provision.py. Gitignored. These also live in Railway.\n"
            f"DB_ROOT_PASSWORD={hexs(24)}\n"
            f"ADMIN_PASSWORD={hexs(16)}\n")
    os.chmod(ENV_FILE, 0o600)
    print(f"generated {ENV_FILE}")

sec = {}
for line in open(ENV_FILE):
    line = line.strip()
    if line and not line.startswith("#") and "=" in line:
        k, v = line.split("=", 1)
        sec[k] = v

# ---------------------------------------------------------------- project context
PROJECT_ID = json.loads(sh("railway", "status", "--json"))["id"]
ENV_ID = next(
    e["node"]["id"]
    for e in gql("query($id:String!){project(id:$id){environments{edges{node{id name}}}}}",
                 {"id": PROJECT_ID})["project"]["environments"]["edges"]
    if e["node"]["name"] == "production")
print(f"project {PROJECT_ID}  env {ENV_ID}")

CREATE = "mutation($i:ServiceCreateInput!){serviceCreate(input:$i){id name}}"
UPDATE = ("mutation($s:String!,$e:String!,$i:ServiceInstanceUpdateInput!)"
          "{serviceInstanceUpdate(serviceId:$s,environmentId:$e,input:$i)}")


def create(name, *, image=None, repo=None, variables=None, start=None, root=None):
    source = {"image": image} if image else {"repo": repo}
    body = {"projectId": PROJECT_ID, "environmentId": ENV_ID, "name": name,
            "source": source, "variables": variables or {}}
    if repo:
        body["branch"] = "railway"
    sid = gql(CREATE, {"i": body})["serviceCreate"]["id"]
    patch = {}
    if start:
        patch["startCommand"] = start
    if root:
        patch["rootDirectory"] = root
    if patch:
        gql(UPDATE, {"s": sid, "e": ENV_ID, "i": patch})
    print(f"  {name:12} {sid}")
    return sid


def add_volume(service, mount):
    """Link first — `railway volume add -s` panics. Retry through the rate limit."""
    sh("railway", "service", "link", service)
    for _ in range(20):
        p = subprocess.run(["railway", "volume", "add", "-m", mount, "--json"],
                           capture_output=True, text=True)
        if '"id"' in p.stdout:
            print(f"  volume {service} -> {mount}")
            return
        if "too quickly" not in (p.stdout + p.stderr).lower():
            raise SystemExit(f"volume add failed for {service}: {p.stdout}{p.stderr}")
        time.sleep(15)
    raise SystemExit(f"volume add kept rate-limiting for {service}")


# ---------------------------------------------------------------- datastores
print("datastores:")
create("mariadb", image="mariadb:11.8",
       # docker-entrypoint.sh switches to the mysql user before exec'ing mariadbd;
       # calling mariadbd directly runs as root and MariaDB refuses to start.
       start="docker-entrypoint.sh mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake",
       variables={"MYSQL_ROOT_PASSWORD": sec["DB_ROOT_PASSWORD"]})
add_volume("mariadb", "/var/lib/mysql")

create("redis-cache", image="redis:8-alpine")
create("redis-queue", image="redis:8-alpine")

# ---------------------------------------------------------------- erpnext + domain
print("erpnext:")
erpnext = create("erpnext", repo=GH_REPO, root="railway", variables={
    "SITE_NAME": "erpnext",
    "DB_ROOT_PASSWORD": "${{mariadb.MYSQL_ROOT_PASSWORD}}",
    "ADMIN_PASSWORD": sec["ADMIN_PASSWORD"],
    "FRAPPE_SITE_NAME_HEADER": "erpnext",
    "PORT": "8080"})
add_volume("erpnext", "/home/frappe/frappe-bench/sites")

DOMAIN = gql("mutation($i:ServiceDomainCreateInput!){serviceDomainCreate(input:$i){domain}}",
             {"i": {"serviceId": erpnext, "environmentId": ENV_ID, "targetPort": 8080}}
             )["serviceDomainCreate"]["domain"]
print(f"  domain https://{DOMAIN}")

# RAILWAY_PUBLIC_DOMAIN must be set after the domain is known.
# serviceInstanceUpdate doesn't expose a variables field, so use the CLI.
sh("railway", "variables", "set",
   f"RAILWAY_PUBLIC_DOMAIN=https://{DOMAIN}", "-s", "erpnext")

print(f"\nDone. First run: https://{DOMAIN}/app")
print("The erpnext service runs bench new-site on first boot (3-5 min); /app 502s until it finishes.")
print(f"Log in as Administrator with the password in {ENV_FILE}")
